# This is actually a Swift-project.
language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3

before_install:
- xcrun simctl list # list devices

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pushd 40_MVVM_FRP-App/MatchGame/ ; carthage update --platform iOS ; popd

script:
- set -o pipefail
- xcodebuild -project 10_Commandline-App/Matchgame/Matchgame.xcodeproj -scheme Matchgame build | xcpretty -c
- xcodebuild -project 20_Basic-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" clean build | xcpretty -c || true
- xcodebuild -project 20_Basic-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" test | xcpretty -c
- xcodebuild -project 30_MVVM-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" clean build | xcpretty -c || true
- xcodebuild -project 30_MVVM-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" test | xcpretty -c
- xcodebuild -project 40_MVVM_FRP-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" clean build | xcpretty -c || true
- xcodebuild -project 40_MVVM_FRP-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame -sdk iphonesimulator9.3 -destination "OS=9.3,name=iPhone 6" test | xcpretty -c

