# This is actually a Swift-project.
language: objective-c
osx_image: xcode8.2

before_install:
- xcrun simctl list # list devices

install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pushd 40_MVVM_FRP-App/MatchGame/ ; carthage update --platform iOS ; popd

script:
- set -o pipefail
- xcodebuild -project 10_Commandline-App/Matchgame/Matchgame.xcodeproj -scheme Matchgame build | xcpretty -c
- xcodebuild -project 20_Basic-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" clean build | xcpretty -c || true
- xcodebuild -project 20_Basic-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" test | xcpretty -c
- xcodebuild -project 30_MVVM-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" clean build | xcpretty -c || true
- xcodebuild -project 30_MVVM-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" test | xcpretty -c
- xcodebuild -project 40_MVVM_FRP-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" clean build | xcpretty -c || true
- xcodebuild -project 40_MVVM_FRP-App/Matchgame/Matchgame.xcodeproj -scheme MatchGame CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination "platform=iOS Simulator,OS=10.1,name=iPhone SE" test | xcpretty -c

